import fs from 'fs';
import path from 'path';
import { logger } from './logger.js';

const DATA_DIR = process.env.DATA_DIR || './config';
const DEFAULT_STATS_PATH = path.join(DATA_DIR, 'facts-serve-stats.json');
const WINDOW_MS = 24 * 60 * 60 * 1000;

interface PersistedStats {
  /** Epoch ms of cache serves */
  cacheHits: number[];
  /** Epoch ms of successful AI generations */
  generations: number[];
}

export interface FactsServeStatsSnapshot {
  windowHours: number;
  cacheHits: number;
  generations: number;
  total: number;
  cacheHitPercent: number;
  generationPercent: number;
}

/**
 * Rolling 24h counters for facts served from cache vs newly generated by AI.
 * Timestamps are pruned on read/write and persisted so restarts keep the window.
 */
export class FactsServeStats {
  private cacheHits: number[] = [];
  private generations: number[] = [];
  private statsPath: string;
  private saveTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(statsPath: string = DEFAULT_STATS_PATH) {
    this.statsPath = statsPath;
    this.load();
  }

  private load(): void {
    try {
      if (!fs.existsSync(this.statsPath)) return;
      const raw = JSON.parse(fs.readFileSync(this.statsPath, 'utf-8')) as Partial<PersistedStats>;
      this.cacheHits = Array.isArray(raw.cacheHits)
        ? raw.cacheHits.filter((t) => typeof t === 'number' && Number.isFinite(t))
        : [];
      this.generations = Array.isArray(raw.generations)
        ? raw.generations.filter((t) => typeof t === 'number' && Number.isFinite(t))
        : [];
      this.prune();
    } catch (error) {
      logger.error(`Failed to load facts serve stats: ${error}`);
    }
  }

  private prune(now: number = Date.now()): void {
    const cutoff = now - WINDOW_MS;
    this.cacheHits = this.cacheHits.filter((t) => t >= cutoff);
    this.generations = this.generations.filter((t) => t >= cutoff);
  }

  private scheduleSave(): void {
    if (this.saveTimer) clearTimeout(this.saveTimer);
    this.saveTimer = setTimeout(() => {
      this.saveTimer = null;
      this.save();
    }, 500);
  }

  private save(): void {
    try {
      const dir = path.dirname(this.statsPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      this.prune();
      const data: PersistedStats = {
        cacheHits: this.cacheHits,
        generations: this.generations,
      };
      fs.writeFileSync(this.statsPath, JSON.stringify(data, null, 2));
    } catch (error) {
      logger.error(`Failed to save facts serve stats: ${error}`);
    }
  }

  recordCacheHit(): void {
    this.cacheHits.push(Date.now());
    this.prune();
    this.scheduleSave();
  }

  recordGeneration(): void {
    this.generations.push(Date.now());
    this.prune();
    this.scheduleSave();
  }

  snapshot(): FactsServeStatsSnapshot {
    this.prune();
    const cacheHits = this.cacheHits.length;
    const generations = this.generations.length;
    const total = cacheHits + generations;
    return {
      windowHours: 24,
      cacheHits,
      generations,
      total,
      cacheHitPercent: total > 0 ? Math.round((cacheHits / total) * 1000) / 10 : 0,
      generationPercent: total > 0 ? Math.round((generations / total) * 1000) / 10 : 0,
    };
  }
}
